#### Homework 1:

Question1: Pandas version

In [1]:
import numpy as np
import pandas as pd

In [2]:
print(pd.__version__)

3.0.5


Getting the data :

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.to_csv('car_fuel_efficiency.csv')

In [5]:
df = pd.read_csv('car_fuel_efficiency.csv', index_col=0)

In [6]:
print(df.head())

   model_year  origin fuel_type         drivetrain  num_doors  \
0        2006  Europe  Gasoline  Front-wheel drive          4   
1        2008  Europe    Diesel  Front-wheel drive          4   
2        1996    Asia  Gasoline  Front-wheel drive          5   
3        1989  Europe  Gasoline  Front-wheel drive          4   
4        1994     USA    Diesel  Front-wheel drive          3   

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2180              6       243.0            3870   
1                 2390              6       272.0            4210   
2                 2320              6       267.0            4240   
3                 2130              6       258.0            4490   
4                 2580              7       304.0            4510   

   acceleration  fuel_efficiency_mpg  
0           NaN                 31.9  
1           NaN                 31.3  
2          17.3                 27.5  
3          18.7                 28.5  

In [7]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   model_year           10000 non-null  int64  
 1   origin               10000 non-null  str    
 2   fuel_type            10000 non-null  str    
 3   drivetrain           10000 non-null  str    
 4   num_doors            10000 non-null  int64  
 5   engine_displacement  10000 non-null  int64  
 6   num_cylinders        10000 non-null  int64  
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64  
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), str(3)
memory usage: 859.5 KB
None


In [8]:
df_describe = df.describe(include='all')
print(df_describe)

          model_year origin fuel_type         drivetrain    num_doors  \
count   10000.000000  10000     10000              10000  10000.00000   
unique           NaN      3         3                  3          NaN   
top              NaN    USA  Gasoline  Front-wheel drive          NaN   
freq             NaN   4202      6913               5519          NaN   
mean     1999.549500    NaN       NaN                NaN      3.50400   
std        14.207925    NaN       NaN                NaN      0.95209   
min      1975.000000    NaN       NaN                NaN      2.00000   
25%      1987.000000    NaN       NaN                NaN      3.00000   
50%      2000.000000    NaN       NaN                NaN      4.00000   
75%      2012.000000    NaN       NaN                NaN      4.00000   
max      2024.000000    NaN       NaN                NaN      5.00000   

        engine_displacement  num_cylinders   horsepower  vehicle_weight  \
count          10000.000000   10000.000000  9123

Question2 : Records count

In [9]:
n = len(df)
print('Records count is : {}'.format(n))

Records count is : 10000


Question3 : Fuel types

In [10]:
print(df.fuel_type.unique())

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str


In [11]:
fuel_types_num = df.fuel_type.nunique()

In [12]:
print('Fuel types number is : {}'.format(fuel_types_num))

Fuel types number is : 3


Question4 : Missing values

In [13]:
df_missing_values = df.isnull().sum().reset_index().rename(columns={'index':'feature', 0:'Nan_count'})

In [14]:
print(df_missing_values)

                feature  Nan_count
0            model_year          0
1                origin          0
2             fuel_type          0
3            drivetrain          0
4             num_doors          0
5   engine_displacement          0
6         num_cylinders          0
7            horsepower        877
8        vehicle_weight          0
9          acceleration        264
10  fuel_efficiency_mpg          0


In [15]:
df_missing_values_features = df_missing_values[df_missing_values.Nan_count > 0]
print(df_missing_values_features)

        feature  Nan_count
7    horsepower        877
9  acceleration        264


In [16]:
lst = list(df_missing_values_features.feature)
#print(lst)
print('The features having missing values are in this list : {}'.format(lst))

The features having missing values are in this list : ['horsepower', 'acceleration']


In [17]:
print('In this dataset, there is {} columns having missing values'.format(len(lst)))

In this dataset, there is 2 columns having missing values


Question5: Max fuel efficiency

In [18]:
Max_fuel_efficiency = df.fuel_efficiency_mpg.max() #import numpy as np np.max(fuel_efficiency_mpg)
print('Max fuel efficiency is : {}'.format(Max_fuel_efficiency))

Max fuel efficiency is : 41.2


Question6: Median value of horsepower

In [19]:
median_horsepower = df.horsepower.median() ##import numpy as np np.median(horsepower)
print(median_horsepower)

254.0


In [20]:
horsepower_value_counts = df.horsepower.value_counts(dropna=False)
print(horsepower_value_counts)

horsepower
NaN      877
252.0    174
246.0    168
256.0    168
259.0    165
        ... 
322.0      1
330.0      1
175.0      1
178.0      1
320.0      1
Name: count, Length: 154, dtype: int64


In [21]:
horsepower_most_frequent_value = list(df.horsepower.value_counts(dropna=True).reset_index().horsepower)[0]
#horsepower_most_frequent_value = list(df.horsepower.value_counts(dropna=True).reset_index().iloc[0])[0]
horsepower_most_frequent_value

252.0

In [22]:
df = df.fillna({'horsepower': horsepower_most_frequent_value})

In [23]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [24]:
new_horsepower_value_counts = df.horsepower.value_counts(dropna=False)
new_horsepower_value_counts

horsepower
252.0    1051
246.0     168
256.0     168
259.0     165
253.0     165
         ... 
322.0       1
330.0       1
175.0       1
178.0       1
320.0       1
Name: count, Length: 153, dtype: int64

In [25]:
new_median_horsepower = df.horsepower.median() ##import numpy as np np.median(horsepower)
print(new_median_horsepower)

252.0


In [26]:
def median_evolution(new, old):
    sentence = ''
    if new > old:
        sentence = 'The median has increased'
    elif new < old:
        sentence = 'The median has decreased'
    else:
        sentence = 'No change in median'
    return sentence

In [27]:
print(median_evolution(new_median_horsepower, median_horsepower))

The median has decreased


Question7: Sum of weights

In [28]:
asia_cars = df[df.origin == 'Asia'].reset_index(drop=True)
print(asia_cars.head())

   model_year origin fuel_type         drivetrain  num_doors  \
0        1996   Asia  Gasoline  Front-wheel drive          5   
1        1992   Asia  Gasoline  Front-wheel drive          2   
2        1997   Asia  Gasoline   Rear-wheel drive          3   
3        1978   Asia  Gasoline    All-wheel drive          3   
4        2007   Asia    Diesel  Front-wheel drive          4   

   engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                 2320              6       267.0            4240   
1                 2270              6       250.0            4310   
2                 2330              6       251.0            4230   
3                 2410              6       252.0            4420   
4                 2170              5       226.0            3950   

   acceleration  fuel_efficiency_mpg  
0          17.3                 27.5  
1          21.7                 26.8  
2          19.5                 30.9  
3          19.5                 26.8  
4    

In [29]:
asia_vehicle_weight_model_year = asia_cars[['vehicle_weight', 'model_year']]
print(asia_vehicle_weight_model_year)

      vehicle_weight  model_year
0               4240        1996
1               4310        1992
2               4230        1997
3               4420        1978
4               3950        2007
...              ...         ...
2989            4610        2011
2990            4530        2004
2991            3630        1975
2992            4610        1993
2993            4370        1993

[2994 rows x 2 columns]


In [30]:
asia_vehicle_weight_model_year_7vals = asia_vehicle_weight_model_year.head(7)
print(asia_vehicle_weight_model_year_7vals)

   vehicle_weight  model_year
0            4240        1996
1            4310        1992
2            4230        1997
3            4420        1978
4            3950        2007
5            4750        2021
6            4450        2019


In [31]:
X = np.array(asia_vehicle_weight_model_year_7vals)
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]


In [32]:
XTX = (X.T)@X
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]


In [33]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
print(y)

[1100 1300  800  900 1000 1100 1200]


In [34]:
if np.linalg.det(XTX) != 0:
    XTX_inv = np.linalg.inv(XTX)
    W = (XTX_inv)@(X.T)@y
    print('W = {}'.format(W))
else:
    print('The XTX matrix is not inersible !!!')

W = [0.13644777 0.2327492 ]


In [35]:
W_sum = W.sum()
print(W_sum)

0.36919696904925486


In [36]:
W_sum = np.sum(W)
print(W_sum)

0.36919696904925486
